### ISSUE TITLE
error, once replacing at least 1 wem file, the exported .bnk doesn't work

### ISSUE THREAD

**Issue by DevolasRevenge** [hpxro7/bnkutil#18]
![image](https://user-images.githubusercontent.com/49737689/104407454-9e254a80-552f-11eb-86bc-1266cc808760.png)

hello, I seem to have run into an issue myself. Not sure if it's something i'm doing wrong on my end. I replaced 1 .wem file from a .bnk with a .wem file that i've converted from an .ogg to a .wav file (used audacity to convert to .wav, then wwise to convert to .wem. Everything so far is fine, i replace the file, it says it's exported, and the new file appears perfectly.

When I tried to inject it into DMC5 i noticed that none of the sounds in that file were working. I tried reimporting that exported file into wwiseutil and i got that error. 

[Not sure if this is worth anything but the .wem i replaced was both smaller in time & kb than the previous file, but the resulting exported .bnk was 7kb bigger than the original file]

hopefully you can point out something I did wrong in my steps, thanks I appreciate the tool!

**Comment by Extendoz** [comment]
> ![image](https://user-images.githubusercontent.com/49737689/104407454-9e254a80-552f-11eb-86bc-1266cc808760.png)
> 
> hello, I seem to have run into an issue myself. Not sure if it's something i'm doing wrong on my end. I replaced 1 .wem file from a .bnk with a .wem file that i've converted from an .ogg to a .wav file (used audacity to convert to .wav, then wwise to convert to .wem. Everything so far is fine, i replace the file, it says it's exported, and the new file appears perfectly.
> 
> When I tried to inject it into DMC5 i noticed that none of the sounds in that file were working. I tried reimporting that exported file into wwiseutil and i got that error.
> 
> [Not sure if this is worth anything but the .wem i replaced was both smaller in time & kb than the previous file, but the resulting exported .bnk was 7kb bigger than the original file]
> 
> hopefully you can point out something I did wrong in my steps, thanks I appreciate the tool!

did you figure this out? I am in the same situation

**Comment by DevolasRevenge** [comment]
> 

The issue is the way the tool packs the new bnk. I suggest you use a different tool for this. I used one recently made for REengine games such as DMC5 (the game that i'm modding), but i've also used it for another game as well and it worked just fine. It's called [RingingBloom ](https://github.com/Silvris/RingingBloom) @Extendoz

**Comment by Extendoz** [comment]
> > 
> 
> The issue is the way the tool packs the new bnk. I suggest you use a different tool for this. I used one recently made for REengine games such as DMC5 (the game that i'm modding), but i've also used it for another game as well and it worked just fine. It's called [RingingBloom ](https://github.com/Silvris/RingingBloom) @Extendoz

bro i cant thank you enough! its not corrupting my files which is great but its reading the .wems starting at 0 which is causing me issues and its missing a few .wem files. Ive replaced the .wems but its not changing the in game sound for that .wem unfortunately. idk if you have any idea on some tips for this RingingBloom @mynameis2cool4u

**Comment by Extendoz** [comment]
i think its messing up all the offsets with it being like that

**Comment by DevolasRevenge** [comment]
I'm not sure about your issue, what game are you trying to mod audio for?

**Comment by Extendoz** [comment]
Pokemon Legends Arceus

**Comment by Extendoz** [comment]
[Mod Files.zip](https://github.com/hpxro7/wwiseutil/files/8019302/Mod.Files.zip)

**Comment by Extendoz** [comment]
omg im an idiot

**Comment by Extendoz** [comment]
it was deleting the underscore when exporting

**Comment by Extendoz** [comment]
sorry lol and thank you so fucking much! youre a life saver!!!!
